# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod "ESPullToRefresh"
  pod "ActiveLabel"

  target 'TwitterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
